services:
  # Loki Service
  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml

  # Promtail Service
  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./var/promtail-config.yaml:/etc/promtail/config.yaml
      - ./reports:/reports # Bind mount the report schemas folder
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  # Grafana Service
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - promtail

volumes:
  grafana-data:

