# Use this docker-compose file to run Playwright tests against the PS API services in a 
# container. The services must first be run via the docker-compose.local.yml file in order 
# to use the external network created by that file.

services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.48.0-focal
    volumes:
      - ./test/playwright:/playwright
    working_dir: /playwright
    environment:
      - ENV=CI
      - BASEURL=http://graphql:8080/graphql
    command: sh -c "mkdir -p coverage && npm install && npm run codegen && npm run test"
    networks:
      - pstatus-local_shared

networks:
  pstatus-local_shared:
    external: true
