name: pstatus-api-core

services:
  graphql:
    image: quay.io/us-cdcgov/phdo/pstatus-graphql:latest
    env_file:
      - .env.local
    networks:
      - core-services
    ports:
      - "127.0.0.1:8090:8080" # GraphQL listener port
    environment:
      SECURITY_ENABLED: false
      MSG_SYSTEM: "rabbitmq"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 5672
      RABBITMQ_VALIDATED_REPORT_QUEUE_NAME: "ValidatedReportQueue"
      RABBITMQ_USERNAME: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_VIRTUAL_HOST: "/"
      FORWARD_VALIDATED_REPORTS: "${FORWARD_VALIDATED_REPORTS:-false}"
      DATABASE: "couchbase"
      COUCHBASE_CONNECTION_STRING: "couchbase://couchbase"
      COUCHBASE_USERNAME: "admin"
      COUCHBASE_PASSWORD: "password"
      REPORT_SCHEMA_LOADER_SYSTEM: "file_system"
      REPORT_SCHEMA_LOCAL_FILE_SYSTEM_PATH: "/reports"
      PSTATUS_RULES_ENGINE_NOTIFICATIONS_BASE_URL: "http://notifications-rules-engine:8080"
      PSTATUS_WORKFLOW_NOTIFICATIONS_BASE_URL: "http://notifications-workflow:8080"
      SCHEMA_ADMIN_SECRET_TOKEN: "${SCHEMA_ADMIN_SECRET_TOKEN:-LET_ME_IN_PLS_THANKS}"
    depends_on:
      - couchbase
    restart: "always"
    volumes:
      - ./reports:/reports # Bind mount the report schemas folder

  report-sink:
    image: quay.io/us-cdcgov/phdo/pstatus-report-sink:latest
    env_file:
      - .env.local
    networks:
      - core-services
    ports:
      - "127.0.0.1:${SINK_PORT:-8080}:8080" # Rest API listener port
    environment:
      DATABASE: "couchbase"
      COUCHBASE_CONNECTION_STRING: "couchbase://couchbase"
      COUCHBASE_USERNAME: "admin"
      COUCHBASE_PASSWORD: "password"
      MSG_SYSTEM: "RABBITMQ"
      RABBITMQ_EXCHANGE_TOPIC_NAME: "PSAPIExchange"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 5672
      RABBITMQ_REPORT_QUEUE_NAME: "PSAPIQueue"
      RABBITMQ_VALIDATED_REPORT_QUEUE_NAME: "ValidatedReportQueue"
      RABBITMQ_ROUTING_KEY: "psapi1234"
      RABBITMQ_USERNAME: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_VIRTUAL_HOST: "/"
      FORWARD_VALIDATED_REPORTS: "${FORWARD_VALIDATED_REPORTS:-false}"
      REPORT_SCHEMA_LOADER_SYSTEM: "file_system"
      REPORT_SCHEMA_LOCAL_FILE_SYSTEM_PATH: "/reports"
    depends_on:
      - couchbase
      - rabbitmq
    restart: "always"
    volumes:
      - ./reports:/reports # Bind mount the report schemas folder

  couchbase:
    image: couchbase
    networks:
      - core-services
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    deploy:
      resources:
        limits:
          memory: 4G # Set the memory limit here

  couchbase-setup:
    image: couchbase # use the couchbase image, so we have the couchbase CLI tools preinstalled
    networks:
      - core-services
    depends_on:
      - couchbase
    restart: "no"
    volumes:
      - ./couchbase-init.sh:/scripts/couchbase-init.sh # Mount the setup script
    entrypoint: ["bash", "-c", "/scripts/couchbase-init.sh"]

  rabbitmq:
    image: rabbitmq:management # docker image(with management plugin) to be used for rabbitmq service
    networks:
      - core-services
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

volumes:
  couchbase_data:
    external: false

networks:
  core-services:
    driver: bridge
    name: core-services
