services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.48.0-focal
    volumes:
      - ./test/playwright:/playwright
    working_dir: /playwright
    environment:
      - BASEURL=http://graphql:8080/graphql
    command: sh -c "mkdir -p coverage && npm install && npm run codegen && npm run test"
    networks:
      - pstatus-local_shared

networks:
  pstatus-local_shared:
    external: true