services:
  tempo:
    image: grafana/tempo
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200" # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
      - "9411:9411" # zipkin
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prom-data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
  notifications-workflow:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo
      OTEL_METRICS_EXPORTER: none
  notifications-rules-engine:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo
      OTEL_METRICS_EXPORTER: none
  report-sink:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo
      OTEL_METRICS_EXPORTER: none
  graphql:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo
      OTEL_METRICS_EXPORTER: none

volumes:
  tempo-data:
  prom-data: