services:
  rabbitmq:
    build:
      context: .
      dockerfile: docker-compose/Dockerfile.rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
    volumes:
      - ./docker-compose/rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
      - ./local-data/rabbitmq/data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
      interval: 10s
      timeout: 5s
      retries: 5
