receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:55681"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging] # Loki is removed here since it doesn't support traces
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus] # Loki doesn't support metrics either
