server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "pstatus-api-report-sink"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "pstatus-api-report-sink.*"
        target_label: job
      - source_labels: [__meta_docker_container_name]
        regex: "/?(.*)"
        target_label: container
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            message: msg