name: "TST/STG - Deploy release candidate"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  staging:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: aks-deployment-pstatus-graphql-stg.yml
      REF: '${{ github.ref_name }}'  # Resolves to the tag that is pushed
    secrets: inherit