name: CI - E2E Tests

on:
  workflow_dispatch:
  pull_request:


jobs:
    e2e-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - 