name: "CI - GraphQL Service"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - pstatus-graphql-ktor/**

defaults:
  run:
    working-directory: pstatus-graphql-ktor/

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pstatus-graphql-ktor/
    steps:
      - uses: actions/checkout@v4
      - name: Run Gradle jib
        run: ./gradle jib
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gradle Test
        run: ./gradle test