name: "CI - Notifications Service"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - pstatus-notifications-rules-engine-ktor/**

defaults:
  run:
    working-directory: pstatus-notifications-rules-engine-ktor/

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gradle Test
        run: |
          chmod +x ./gradlew
          ./gradlew test