name: DEV - Report Service

on:
  workflow_dispatch:
    inputs:
      REF:
        description: Branch from CDCgov/data-exchange-processing-status that you want to deploy to the dev environment.
        default: develop
        required: true
        type: string
  push:
    branches:
        - develop
    paths:
        - pstatus-report-sink-ktor/**

jobs:
  remote-trigger:
    uses: ./.github/workflows/remote-cd-trigger-template.yml
    with:
      WORKFLOW: report-build-pushImage-dev.yml 
      REF: ${{ inputs.REF }}
    secrets: inherit